-- Practice Question 1

CREATE DATABASE IF NOT EXISTS College;

USE College;

CREATE TABLE Teacher(
	ID INT PRIMARY KEY,
    Name VARCHAR(30) NOT NULL,
    Subject VARCHAR(30) UNIQUE,
    Salary INT DEFAULT 10000
);

INSERT INTO Teacher
(ID, Name, Subject, Salary)
VALUES
(23, "Ajay", "Maths", 50000),
(47, "Bharat", "English", 60000),
(18, "Chetan", "Chemistry", 45000),
(9, "Divya", "Physics", 75000);

SELECT * FROM Teacher;

-- A. SELECT TEACHERS WHOSE SALARY IS MORE THAN 55K

SELECT * FROM Teacher WHERE Salary > 55000;

-- B. RENAME THE SALARY COLUMN TO CTC

ALTER TABLE Teacher CHANGE Salary CTC INT DEFAULT 10000;

-- C. UPDATE SALARY OF ALL TEACHERS BY GIVING THEM AN INCREMENT OF 25%

UPDATE Teacher SET CTC = CTC + (0.25 * CTC);

-- D. ADD A NEW COLUMN CALLED CITY AND GIVE A DEFAULT VALUE SURAT 

ALTER TABLE Teacher ADD COLUMN City VARCHAR(30) DEFAULT "Surat";

-- E. DELETE THE CITY COLUMN

ALTER TABLE Teacher DROP COLUMN City;