-- TRANSACTIONS : SERIES OF OPERATIONS THAT ARE SEEN AS A WHOLE
/*
	4 PROPERTIES OF TRANSACTIONS / DBMS :-
    
    A. ATOMICITY : ALL STATEMENTS MUST SUCCEED OR NONE SHOULD SUCCEED
    B. CONSISTENCY : DATA MOVES FROM ONE VALID STATE TO ANOTHER
    C. ISOLATION : PARALLEL TRANSACTIONS DO NOT INTERFERE
    D. DURABILITY : COMMITTED DATA IS PERMANENTALY SAVED
*/

-- COMMIT : AFTER WRITING THE STEPS OF A TRANSACTION, WE COMMIT IT, WHICH IS LIKE A FINAL CHECK FOR ALL THE STEPS ABOVE
-- ROLLBACK : UNDO ALL THE STEPS ABOVE THAT ARE NOT COMMITED TO MAINTAIN ATOMICITY
-- BY DEFAULT, EACH QUERY IS CONSIDERED AN INDEPENDENT TRASACTION AND IS AUTO COMMITTED, BUT WE NEED TO CHANGE IT FOR CUSTOM TRANSACTION
-- TO CHECK THE VALUE OF THE AUTO COMMIT, WE DO :-

SELECT @@AUTOCOMMIT; -- VALUE IS 1, WHICH MEANS AUTOCOMMIT IS ON
SET AUTOCOMMIT = 0; -- NOW, AUTO COMMIT IS DISABLED, TO ENABLE IT, SET IT BACK TO 1

CREATE DATABASE IF NOT EXISTS Prime;

USE Prime;

CREATE TABLE Accounts(
	ID INT PRIMARY KEY AUTO_INCREMENT,
    Name VARCHAR(30),
    Balance Decimal(10,2)
);

INSERT INTO Accounts
(Name, Balance)
VALUES
("Adam",500.00),
("Bob",300.00),
("Charlie", 1000.00);

SELECT * FROM Accounts;

-- TRANSACATION 1 : SEND 50 DOLLARS FROM ACCOUNT WITH ID = 1 TO ACCOUNT WITH ID = 2

START TRANSACTION; -- TELLS THE MACHINE THIS IS THE OFFICIAL START
UPDATE Accounts SET Balance = Balance - 50.00 WHERE ID = 1; -- CREDIT FROM ID = 1
UPDATE Accounts SET Balance = Balance + 50.00 WHERE ID = 2; -- DEBIT INTO ID = 2
COMMIT; -- COMMIT THE CHANGES

-- TRANSACATION 2 : SEND 100 DOLLARS FROM ACCOUNT WITH ID = 1 TO ACCOUNT WITH ID = 3 BUT DUE TO SYSTEM FAILURE WE NEED TO ROLLBACK 

START TRANSACTION; -- TELLS THE MACHINE THIS IS THE OFFICIAL START
UPDATE Accounts SET Balance = Balance - 100.00 WHERE ID = 1; -- CREDIT FROM ID = 1
UPDATE Accounts SET Balance = Balance + 100.00 WHERE ID = 3; -- DEBIT INTO ID = 3
ROLLBACK; -- UNDO THE CHANGES

-- TRANSACATION 3 : WORSE CASE SCENARIO, AFTER CREDITING THE SYSTEM COMMITTED AND THEN FAILED, NOW ROLLBACK ALSO CANNOT UNDO ALL THE CHANGES 

START TRANSACTION; -- TELLS THE MACHINE THIS IS THE OFFICIAL START
UPDATE Accounts SET Balance = Balance - 100.00 WHERE ID = 1; -- CREDIT FROM ID = 1
COMMIT; -- COMMIT THE CHANGES
UPDATE Accounts SET Balance = Balance + 100.00 WHERE ID = 3; -- DEBIT INTO ID = 3
ROLLBACK; -- UNDO THE CHANGES

-- SAVEPOINT : CHECKPOINT IN A TRANSACTION UNTIL WHERE THE CHANGES ARE GOOD BUT AFTER IT WE MIGHT NEED TO ROLLBACK

-- TRANSACTION 4 : USER TOP UPS 1000 DOLLARS AND THEN GET 10 DOLLAR CASHBACK BUT THERE WAS A FAILURE IN CASHBACK


START TRANSACTION; -- TELLS THE MACHINE THIS IS THE OFFICIAL START
UPDATE Accounts SET Balance = Balance + 1000.00 WHERE ID = 1; -- MAIN TASK, TOPUP OF 1000 DOLLARS
SAVEPOINT WALLET_TOPUP; -- SAVEPOINT
UPDATE Accounts SET Balance = Balance + 10.00 WHERE ID = 1; -- SECONDARY TASK, CASHBACK ERROR
ROLLBACK TO WALLET_TOPUP; -- UNDO BUT ONLY THE CASHBACK ONE
COMMIT;




