-- VIEWS : A VIRTUAL TABLE BASED ON THE RESULT OF AN SQL QUERY, USED TO MAINTAIN PRIVACY

USE Inventory;

SELECT * FROM Orders;
SELECT * FROM Customers;

-- Q1. THE SALES TEAM JUST WANTS THE NAME AND CUSTOMER ID FROM THE CUSTOMER TABLE, SO WE GIVE THEM A VIEW OF IT AND NOT ORIGINAL DATA

CREATE VIEW View1 AS -- MAKE THE VIEW
SELECT Customer_ID, Name FROM Customers; -- VIEW SHOULD HAVE THESE

SELECT * FROM View1; -- A VIEW WILL ACT JUST AS A TABLE SO WE CAN RUN CLAUSES ON IT ASWELL

-- Q2. THE SALES TEAM JUST WANTS THE DATA OF CUSTOMERS WHO HAVE AN ORDER, SO WE MAKE A JOIN AND THEN GIVE THEM A VIEW OF IT

CREATE VIEW View2 AS -- CREATE VIEW
SELECT c.Customer_ID, c.Name -- IN A VIEW WE NEED TO SPECIFY WHICH COLUMNS WE WANT
FROM Customers c
INNER JOIN Orders o
ON c.Customer_ID = o.Customer_ID; -- CREATING THE JOIN

SELECT * FROM View2;

DROP VIEW View1; -- HOW TO DROP A VIEW

-- INDEX : SPECIAL DATABASE OBJECTS THAT MAKE DATA RETRIEVAL FAST, GENERALLY USING PRIMARY KEYS
-- THESE INDEXES MAKE THE SELECT QUERIES FASTER WHEN WE HAVE MILLIONS OF ROWS
-- DRAWBACK : MAKES THE TABLE QUERIES LIKE UPDATE ALTER DELETE ETC SLOW

USE Company;

CREATE TABLE Accounts(
	Account_ID INT PRIMARY KEY,
    Name VARCHAR(30),
    Balance DECIMAL(10,2),
    Branch VARCHAR(50)
);

INSERT INTO Accounts
(Account_ID, Name, Balance, Branch)
VALUES
(1,"Adam",500.00,"Mumbai"),
(2, "Bob", 300.00, "Delhi"),
(3,"Charlie", 700.00, "Bangalore"),
(4,"David", 1000.00, "Surat");

SELECT * FROM Accounts;

-- Q1. WE NEED TO MAKE AN INDEX OF THE BRANCH COLUMN AS IT USED VERY WIDELY TO FETCH DATA

CREATE INDEX idx_Branch -- NAME THE INDEX
ON Accounts(Branch); -- CREATE ON BASIS OF WHICH COLUMN

SHOW INDEX 
FROM Accounts; -- SHOWING INDEX

CREATE INDEX idx_2 
ON Accounts(Branch, Balance); -- COMPOSITE INDEX : MADE UDING MULTIPLE COLUMNS

SHOW INDEX 
FROM Accounts; -- SHOWING COMPOSITE INDEX

DROP INDEX idx_Branch ON Accounts; -- DROPPING INDEX
DROP INDEX idx_2 ON Accounts; -- DROPPING INDEX

-- STORED PROCEDURES : PREDEFINED SET OF STATEMENTS THAT WE CAN SAVE IN THE DATABASE AND EXECUTE WHENEVER NEEDED
				-- NOTE : IT IS JUST LIKE PYTHON FUNCTIONS
                
-- Q1. MAKE A PROCEDURE SO THAT WHENEVER WE ARE ASKED FOR AN ACCOUNT ID WE SHOW THE BALANCE

-- CHANGING DELIMITER VALUE
DELIMITER $$ 

CREATE PROCEDURE Check_Balance(IN Acc_ID INT) -- NAME THE PROCEDURE, NAME THE PARAMTER WITH DATA TYPE WE WILL USE, PREFERABLY USE AN ALIAS 
BEGIN
	SELECT Balance
    FROM Accounts
    WHERE Account_ID = Acc_ID;
END $$ -- WE CHANGE DELIMITER VALUE TO $$ SO THAT SQL DOESNT GET CONFUSED WHEN WE USE ';' INSIDE THE PROCEDURE COMMANDS

-- RESETING DELIMITER VALUE
DELIMITER ; 

CALL Check_Balance(1); -- NOW WE CALL THE PROCEDURE JUST LIKE PYTHON WITH AN INPUT VALUE FOR THE PROCEDURE TO PERFORM THE QUERIES
CALL Check_Balance(2); -- 300 

DROP PROCEDURE IF EXISTS check_Balance; -- DROPPING THE PROCEDURE